version: '3.8'

services:
  # Production FastAPI Yahoo Finance Service
  nifty-yahoo-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nifty-yahoo-api-prod
    ports:
      - "8000:8000"
    environment:
      - FLASK_DEBUG=false
      - CACHE_TIMEOUT=300
      - SECRET_KEY=${SECRET_KEY}
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    command: ["uvicorn", "fastapi_yahoo:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: nifty-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - nifty-yahoo-api
    restart: always
    profiles:
      - with-nginx

networks:
  default:
    name: nifty-analysis-prod
